version: '2'

services:
  demo:
    image: limmiehoang/CircleCI:demo
    container_name: circleci-demo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8088:8081"